name: markov_sd
channels:
  - conda-forge
dependencies:
  - python>=3.11.7

  # framework
  - tensorflow==2.15.0
  - gputil

  # meltingpot deps
  - absl-py>=2.1.0
  - chex>=0.1.85
  - dm-env>=1.6
  - dm-tree
  - immutabledict>=4.1.0
  - ml-collections>=0.1.1
  - networkx>=3.2.1
  - numpy>=1.26.3
  - pygame>=2.5.2
  - reactivex>=4.0.4


  # reward_transfer deps
  - ray-rllib==2.23.0
  - optuna>=3.5.0
  - pandas>=2.2.0
  - wandb

  - pip
  - pip:
    - dmlab2d==1.0.0
